# -*- coding: utf-8 -*-
"""BMI  CALCULATOR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ktwNIJMgOpniyb7WLfdu6eWZUS1Yhc41
"""

height = float(input("Enter height in cm's : "))
weight = float(input("Enter weight in kg's : "))
BMI = (weight) / (height / 100) ** 2
print("Your BMI is :",end = " ")
print("%.1f" % BMI)
if BMI <= 18.4:
  print("You are UNDERWEIGHT")
elif BMI >= 18.5 and BMI <= 24.9:
  print("You are HEALTHY")
elif BMI >= 25 and BMI <= 29.9:
  print("You are OVERWEIGHT")
else:
  print("You are OBESE")